### ISSUE TITLE
Still TODO in 2.x development

### ISSUE THREAD

**Issue by jcupitt** [libvips/php-vips#137]
The FFI version is merged to master, the obvious remaining TODOs are:

-  [ ] Support preloading, see https://www.php.net/manual/en/class.ffi.php
-  [ ] Rewrite the enum and doc generator in php.
-  [ ] Add source/target API
-  [ ] Add progress callbacks etc.
-  [ ] Add mutable.
